---
- name: Cybersecurity main
  import_tasks: apt_package.yml
  when: ansible_distribution == "Debian"
  tags:
  - never
  - cybersecurity

- import_tasks: user.yml
  tags:
  - never
  - cybersecurity
