---
- name: Install Google GPG key
  apt_key:
    url: https://dl.google.com/linux/linux_signing_key.pub
    state: present

- name: Add Google Chrome Repo
  apt_repository:
    repo: deb [arch=amd64] https://dl.google.com/linux/chrome/deb/ stable main
    filename: google-chrome
    update_cache: yes

- name: Install Google Chrome
  apt:
    name: google-chrome-stable
    state: latest
