---
- name: Git config
  template:
    src: git/gitconfig.j2
    dest: "/home/{{ pzzl_user.login }}/.gitconfig"
    owner: "{{ pzzl_user.login }}"
    group: "{{ pzzl_user.login }}"
    mode: "0600"
 