---
# gpg2 --list-secret-keys B15515C491917E67 ; echo $?
# sec   rsa3072 2022-04-01 [SC] [expires: 2024-03-31]
#       1ABE9EC34D137104D589BFECB15515C491917E67
# uid           [ultimate] Cees van de Griend <c.vande.griend@gmail.com>
# ssb   rsa3072 2022-04-01 [E] [expires: 2024-03-31]
#
# 0

- name: Check GPG public key
  become: yes
  become_user: "{{ pzzl_user.login }}"
  command: "gpg2 --list-public-keys {{ pzzl_user.gpgsign }}"
  register: gpg_public_key_exist
  ignore_errors: true

- name: Copy GPG public key
  copy:
    src: gpg/public.asc
    dest: /tmp/public.asc
    owner: "{{ pzzl_user.login }}"
    group: "{{ pzzl_user.login }}"
    mode: "0600"
  when: gpg_public_key_exist.rc != 0

- name: Import GPG public key
  become: yes
  become_user: "{{ pzzl_user.login }}"
  command: gpg2 --import /tmp/public.asc 
  register: gpg_public_key_import
  when: gpg_public_key_exist.rc != 0
  

- name: Check GPG secret key
  become: yes
  become_user: "{{ pzzl_user.login }}"
  command: "gpg2 --list-secret-keys {{ pzzl_user.gpgsign }}"
  register: gpg_secret_key_exist
  ignore_errors: true

- name: Copy GPG secret key
  copy:
    src: gpg/secret.asc
    dest: /tmp/secret.asc
    owner: "{{ pzzl_user.login }}"
    group: "{{ pzzl_user.login }}"
    mode: "0600"
  when: gpg_secret_key_exist.rc != 0

- name: Import GPG secret key
  become: yes
  become_user: "{{ pzzl_user.login }}"
  command: gpg2 --import /tmp/secret.asc 
  when: gpg_secret_key_exist.rc != 0



- name: Create GPG Trust
  become: yes
  become_user: "{{ pzzl_user.login }}"
  shell: "gpg2 --export-ownertrust && echo {{ pzzl_user.gpgsign }}:6: > /tmp/trust.asc"
  when: gpg_public_key_exist.rc != 0 or gpg_secret_key_exist.rc != 0 

- name: Import GPG Trust
  become: yes
  become_user: "{{ pzzl_user.login }}"
  command: "gpg2 --import-ownertrust /tmp/trust.asc"
  when: gpg_public_key_exist.rc != 0 or gpg_secret_key_exist.rc != 0 



- name: Delete GPG public key
  file:
    path: /tmp/public.asc
    state: absent

- name: Delete GPG secret key
  file:
    path: /tmp/secret.asc
    state: absent

- name: Delete GPG trust
  file:
    path: /tmp/trust.asc
    state: absent
