---
- name: Desktop main
  import_tasks: apt_package.yml
  when: ansible_distribution == "Debian"
  tags:
  - desktop

- import_tasks: ssh.yml
  tags:
  - desktop

- import_tasks: git.yml
  tags:
  - desktop

- import_tasks: flatpak.yml
  tags:
  - desktop

- name: Visual Studio Code
  import_tasks: vscode.yml
  when: ansible_distribution == "Debian"
  tags:
  - desktop

- name: Google Chrome
  import_tasks: chrome.yml
  when: ansible_distribution == "Debian"
  tags:
  - desktop
