---
- name: Common user {{ pzzl_user.login }}
  user:
    name: "{{ pzzl_user.login }}"
    comment: "{{ pzzl_user.name }}"
    shell: /usr/bin/zsh

- name: Common user authorized key
  authorized_key:
    user: "{{ pzzl_user.login }}"
    key: "{{ pzzl_user.ssh_key_pub }}"
    state: present
